# Generated by Django 5.1.15 on 2026-05-20 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=40)),
                ('kind', models.CharField(choices=[('child', 'Child'), ('adult', 'Adult')], default='child', max_length=8)),
                ('name', models.CharField(max_length=120)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('other', 'Other')], max_length=8)),
                ('environment', models.CharField(choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], max_length=12)),
                ('religion_interest', models.BooleanField(default=False)),
                ('religion', models.CharField(blank=True, default='', max_length=40)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_ts', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='True for the single profile the user has currently selected on this account. Only one row per user should be active; the view layer enforces this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdata_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EarnedMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_id', models.CharField(max_length=80)),
                ('earned_at', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='userdata.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('how_to_md', models.TextField(blank=True, default='')),
                ('parent_note_md', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tasks', to='userdata.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_free', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_rewards', to='userdata.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RewardUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_category', models.CharField(max_length=80)),
                ('reward_title', models.CharField(max_length=200)),
                ('used_at', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_usages', to='userdata.profile')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160)),
                ('value', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_items', to='userdata.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_slug', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('completed', 'Completed'), ('skipped_known', 'Skipped Known'), ('skipped_unsuitable', 'Skipped Unsuitable'), ('bypassed', 'Bypassed')], default='unlocked', max_length=24)),
                ('repetitions_done', models.PositiveIntegerField(default=0)),
                ('reward_title', models.CharField(blank=True, default='', max_length=200)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='userdata.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('user', 'client_id'), name='userdata_profile_user_client_unique'),
        ),
        migrations.AddConstraint(
            model_name='earnedmastery',
            constraint=models.UniqueConstraint(fields=('profile', 'mastery_id'), name='userdata_mastery_profile_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='customtask',
            constraint=models.UniqueConstraint(fields=('profile', 'client_id'), name='userdata_customtask_profile_client_unique'),
        ),
        migrations.AddConstraint(
            model_name='customreward',
            constraint=models.UniqueConstraint(fields=('profile', 'client_id'), name='userdata_customreward_profile_client_unique'),
        ),
        migrations.AddIndex(
            model_name='rewardusage',
            index=models.Index(fields=['profile', '-used_at'], name='userdata_re_profile_08ce15_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionitem',
            constraint=models.UniqueConstraint(fields=('profile', 'key'), name='userdata_sessionitem_profile_key_unique'),
        ),
        migrations.AddIndex(
            model_name='taskprogress',
            index=models.Index(fields=['profile', 'status'], name='userdata_ta_profile_f84d1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskprogress',
            constraint=models.UniqueConstraint(fields=('profile', 'task_slug'), name='userdata_progress_profile_slug_unique'),
        ),
    ]
