# Generated by Django 5.1.15 on 2026-04-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('household', 'Household'), ('digital', 'Digital'), ('navigation', 'Navigation'), ('cognitive', 'Cognitive')], max_length=16)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('how_to_md', models.TextField(help_text='Markdown. Step-by-step for the parent-facilitated session.')),
                ('safety_md', models.TextField(blank=True, help_text='Markdown. Risks and mitigations. Required for Navigation / Digital tasks.')),
                ('min_age', models.PositiveSmallIntegerField(default=7)),
                ('max_age', models.PositiveSmallIntegerField(default=11)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environments', models.ManyToManyField(blank=True, related_name='tasks', to='content.environment')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='content.tag')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PrerequisiteEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('from_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='content.task')),
                ('to_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='content.task')),
            ],
            options={
                'ordering': ['to_task', 'from_task'],
                'unique_together': {('from_task', 'to_task')},
            },
        ),
        migrations.CreateModel(
            name='TaskCompletionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_band', models.CharField(choices=[('7_8', '7–8'), ('9_10', '9–10'), ('11', '11')], max_length=8)),
                ('environment', models.CharField(choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_events', to='content.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'age_band', 'environment'], name='content_tas_task_id_9eda61_idx')],
            },
        ),
    ]
