# Generated by Django 5.1.15 on 2026-04-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_task_parent_note_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sex_filter',
            field=models.CharField(choices=[('any', 'Any'), ('male', 'Male only'), ('female', 'Female only')], default='any', help_text="Which sex this task applies to. 'Any' means suitable for all.", max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_age',
            field=models.PositiveSmallIntegerField(default=13),
        ),
    ]
