# Generated by Django 5.1.15 on 2026-04-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_add_sex_filter_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repetitions_required',
            field=models.PositiveSmallIntegerField(default=3, help_text='How many times the child must complete this task before it is marked done.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('financial', 'Financial'), ('household', 'Household'), ('digital', 'Digital'), ('navigation', 'Navigation'), ('cognitive', 'Cognitive'), ('social', 'Social')], max_length=16),
        ),
    ]
