# Generated by Django 5.1.15 on 2026-04-18 10:22

from django.db import migrations


def set_repetitions_by_category(apps, schema_editor):
    Task = apps.get_model('content', 'Task')
    # repetitions per category: cognitive=2, digital=2, financial=4, household=5, navigation=3, social=4
    for category, reps in [
        ('cognitive', 2),
        ('digital', 2),
        ('financial', 4),
        ('household', 5),
        ('navigation', 3),
        ('social', 4),
    ]:
        ids = Task.objects.filter(tags__category=category).values_list('id', flat=True).distinct()
        Task.objects.filter(id__in=ids).update(repetitions_required=reps)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_add_repetitions_required'),
    ]

    operations = [
        migrations.RunPython(set_repetitions_by_category, migrations.RunPython.noop),
    ]
