# Generated by Django 5.1.15 on 2026-04-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_set_repetitions_by_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='religion',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Religion id ('islam', 'christianity', etc) — filters task so only profiles that opted in with a matching religion see it. Empty = universal (shown to everyone).", max_length=24),
        ),
    ]
