# Generated by Django 5.1.15 on 2026-04-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('time', 'Time'), ('experience', 'Experience'), ('material', 'Material')], max_length=16, unique=True)),
                ('display_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'reward categories',
            },
        ),
        migrations.CreateModel(
            name='RewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('min_age', models.PositiveSmallIntegerField(default=7)),
                ('max_age', models.PositiveSmallIntegerField(default=11)),
                ('is_free', models.BooleanField(default=True, help_text='Zero monetary cost to the parent.')),
                ('notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='rewards.rewardcategory')),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
